# Generated by Django 4.2 on 2023-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ManyToManyField(related_name='categories', to='testapi.content')),
            ],
        ),
    ]
